//
// Created by Justin on 4/24/16.
//

#ifndef CUSTOMMEMORYMANAGEMENT_DEFINITIONS_H
#define CUSTOMMEMORYMANAGEMENT_DEFINITIONS_H

// forward declaration
class Node;

#define MEMMG_WIDTH 5
#define MEMMG_TYPE Node

#endif //CUSTOMMEMORYMANAGEMENT_DEFINITIONS_H
